# Generated by Django 4.0.1 on 2022-03-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedNames',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=150, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('nwdb_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'confirmed_names',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='nodes',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
            ], options={
                "db_table": "nodes"
            }
        ),
        migrations.CreateModel(
            name='Perks',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, db_column='NAME', max_length=50, null=True)),
            ], options={
                "db_table": "perks"
            }
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('avail', models.IntegerField(blank=True, null=True)),
                ('gs', models.IntegerField(blank=True, null=True)),
                ('perks', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('name_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('server_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prices',
            },
        ),
        migrations.CreateModel(
            name='Name_cleanup',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('bad_word', models.CharField(blank=True, max_length=150, null=True)),
                ('good_word', models.CharField(blank=True, max_length=150, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'name_cleanup',
            },
        ),
        migrations.CreateModel(
            name='nwdb_lookup',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('item_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'nwdb_lookup',
            },
        ),
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('server_id', models.IntegerField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True))
            ],
            options={
                'db_table': 'runs',
            },
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'servers',
            },
        ),
    ]
