# Generated by Django 4.0.1 on 2022-01-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedNames',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=50, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'confirmed_names',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('loc', models.FloatField(blank=True, db_column='LOC', null=True)),
                ('type', models.CharField(blank=True, db_column='TYPE', max_length=50, null=True)),
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('dir', models.IntegerField(blank=True, db_column='DIR', null=True)),
            ],
            options={
                'db_table': 'nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perks',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=50, null=True)),
            ],
            options={
                'db_table': 'perks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('avail', models.IntegerField(blank=True, null=True)),
                ('gs', models.IntegerField(blank=True, null=True)),
                ('perks', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prices',
                'managed': False,
            },
        ),
    ]
