# Generated by Django 4.0.1 on 2022-03-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='name_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
