# Generated by Django 4.0.1 on 2022-03-22 15:35
import datetime
from typing import Tuple

from django.db import connection, migrations, models
import django.db.models.deletion
from django.db.migrations.state import StateApps


def update_run_ids_for_ts_range(run_id: int, obj_dict: dict) -> None:
    start_date = obj_dict["start_date"].isoformat().replace("T", " ")
    end_date = obj_dict["end_date"].isoformat().replace("T", " ")
    server_id = obj_dict["server_id"]
    with connection.cursor() as cursor:
        cursor.execute(f"""
        UPDATE prices
        SET run_id={run_id}
        WHERE
            server_id={server_id} AND
            timestamp BETWEEN '{start_date}' AND '{end_date}'
        """)
    print(f"Updated run id {run_id}")


def forwards(apps: StateApps, schema_editor):
    Run = apps.get_model("nwmarketapp", "Run")  # noqa
    Prices = apps.get_model("nwmarketapp", "Prices")  # noqa
    unique_server_ids = set([value[0] for value in Run.objects.all().values_list("server_id").distinct()])
    run_timestamp_ranges = {}
    for server_id in unique_server_ids:
        all_runs_for_server = Run.objects.filter(server_id=server_id).order_by("id")
        last_server_run_id: int = None
        for run in all_runs_for_server:
            if run.server_id not in run_timestamp_ranges:
                run_timestamp_ranges[run.server_id] = {}
            server_timestamp_ranges = run_timestamp_ranges[run.server_id]
            server_timestamp_ranges[run.id] = {
                "server_id": server_id,
                "start_date": run.start_date,
                "end_date": datetime.datetime.max,
                "previous_run_id": last_server_run_id
            }
            if last_server_run_id is not None:
                server_timestamp_ranges[last_server_run_id]["end_date"] = run.start_date - datetime.timedelta(seconds=1)
            last_server_run_id = run.id

    for server_id, runs in run_timestamp_ranges.items():
        for run_id, run in runs.items():
            update_run_ids_for_ts_range(run_id, run)


def backwards(apps: StateApps, schema_editor):
    pass  # column will be dropped


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0002_remove_tz_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RenameModel(
            old_name='Runs',
            new_name='Run',
        ),
        migrations.RenameModel(
            old_name='Name_cleanup',
            new_name='NameCleanup',
        ),
        migrations.RenameModel(
            old_name='nwdb_lookup',
            new_name='NWDBLookup',
        ),
        migrations.AddField(
            model_name='prices',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nwmarketapp.run'),
        ),
        migrations.AlterField(
            model_name='run',
            name='username',
            field=models.CharField(blank=True, db_column='username', max_length=100, null=True),
        ),
        migrations.RunPython(forwards, backwards)
    ]
