# Generated by Django 4.0.1 on 2022-03-24 08:11

from django.db import migrations, models
from django.db.migrations.state import StateApps


def forwards(apps: StateApps, schema_editor):
    Run = apps.get_model("nwmarketapp", "Run")  # noqa
    Prices = apps.get_model("nwmarketapp", "Price")  # noqa

    prices = Prices.objects.all().values("run_id", "username").distinct()
    Prices.objects.filter(avail=None).update(avail=0)
    for price in prices:
        r = Run.objects.get(id=price["run_id"])
        r.username = price["username"]
        r.save()

    Run.objects.filter(username=None).update(username="empty_run_delete_me")


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('nwmarketapp', '0004_migrate_prices_add_run_id'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name='price',
            name='gs',
        ),
        migrations.RemoveField(
            model_name='price',
            name='perks',
        ),
        migrations.AlterField(
            model_name='price',
            name='approved',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='avail',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='price',
            name='name_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='server_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='run',
            name='approved',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='server_id',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='start_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='username',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
