# Generated by Django 4.0.1 on 2022-03-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0005_populate_null_values_of_nullable_cols'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='scraper_version',
            field=models.CharField(default='unknown', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
