# Generated by Django 4.0.1 on 2022-03-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0006_run_scraper_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='tz_name',
            field=models.TextField(editable=False, null=True),
        ),
    ]
