# Generated by Django 4.0.1 on 2022-03-29 23:07

from django.db import connection, migrations, models
import django.utils.timezone


def forwards(apps, schema_editor):
    unknown_tzs_map = [
        ("january", "America/Los_Angeles"),
        ("solarwhale", "US/Pacific"),
        ("triplepawns", "America/Los_Angeles"),
        ("synaptik", "US/Eastern")
     ]
    with connection.cursor() as cursor:
        q = "CASE\n"
        for username, tz in unknown_tzs_map:
            q += f"  WHEN username='{username}' THEN '{tz}'\n"
        q += "END"
        usernames = ", ".join([f"'{username}'" for username, _ in unknown_tzs_map])
        cursor.execute(f"""UPDATE runs SET tz_name={q} WHERE username IN ({usernames})""")
        cursor.execute(f"""
            UPDATE runs
            SET tz_name=max_tz_name
            FROM (
                select username, max(tz_name) as max_tz_name
                from runs
                group by 1
            ) runs_agg 
            where runs_agg.username=runs.username;
        """)
        cursor.execute(f"""
            UPDATE runs
            SET started_at=start_date at time zone tz_name
        """)
        cursor.execute(f"""
            UPDATE prices
            SET price_timestamp=timestamp at time zone tz_name
            FROM (
                SELECT id as run_id, tz_name
                from runs
            ) runs
            where runs.run_id = prices.run_id
        """)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0007_run_tz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='price_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(forwards, backwards),
        # migrations.RemoveField(
        #     model_name='run',
        #     name='start_date',
        # ),
        # migrations.RemoveField(
        #     model_name='price',
        #     name='timestamp',
        # ),

    ]
