# Generated by Django 4.0.1 on 2022-04-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0008_namecleanupv2'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='name_accuracy',
            field=models.DecimalField(decimal_places=1, editable=False, max_digits=4, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='price_accuracy',
            field=models.DecimalField(decimal_places=1, editable=False, max_digits=4, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='resolution',
            field=models.CharField(default='1440p', editable=False, max_length=50),
        ),
    ]
