# Generated by Django 4.0.1 on 2022-04-01 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def forwards(apps, schema_editor):
    NameCleanup = apps.get_model("nwmarketapp", "NameCleanup")  # noqa
    User = apps.get_model("auth", "User")  # noqa

    for obj in NameCleanup.objects.all():
        bad_string = obj.bad_word
        if not bad_string or bad_string.replace(" ", "") == "" or not obj.good_word:
            obj.delete()
            continue
        bad_words = bad_string.split(" ")
        if len(bad_words) != 1:
            obj.delete()
            continue
        bad_word = bad_words[0]
        obj.bad_word = bad_word
        obj.user = User.objects.get(username=obj.username)
        obj.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nwmarketapp', '0008_namecleanupv2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namecleanup',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='namecleanup',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='namecleanup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='namecleanup',
            name='bad_word',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='namecleanup',
            name='good_word',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='namecleanup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='namecleanup',
            name='username',
        ),
    ]
