# Generated by Django 4.0.1 on 2022-04-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0009_run_name_accuracy_run_price_accuracy_run_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmednames',
            name='max_stack',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='confirmednames',
            name='type_name',
            field=models.TextField(default=None, null=True),
        ),
    ]
