# Generated by Django 4.0.1 on 2022-09-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0011_pricesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_name', to='nwmarketapp.confirmednames')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_name', to='nwmarketapp.confirmednames')),
            ],
            options={
                'db_table': 'crafts',
            },
        ),
    ]
