# Generated by Django 4.0.1 on 2022-11-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0015_fix_crafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='section_name',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
