# Generated by Django 4.0.1 on 2022-11-24 09:20

from django.db import migrations, models
from django.db import connection

def add_sp(apps, schema_editor):
    query = """CREATE OR REPLACE FUNCTION most_comp_top9("s_id" int)
            RETURNS table ("name" varchar,"count" bigint)
            LANGUAGE plpgsql
            AS
            $$
                 DECLARE run_ids integer[];
              BEGIN
                 run_ids := ( ARRAY(
                        select max(id) as id
                from runs
                where server_id = s_id
                    and section_name is not null
                group by section_name
                                   ));
                  RETURN query ( select p.name, COUNT(DISTINCT p.price) AS count
                from prices p
                where p.run_id = ANY(run_ids)
                group by p.name
                order by count desc
                limit 9);
              END;
            $$"""
    with connection.cursor() as cursor:
        cursor.execute(query)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0015_fix_crafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='section_name',
            field=models.CharField(editable=False, max_length=100, null=True, default='Raw Resources'),
        ),
        migrations.AddField(
            model_name='run',
            name='session_id',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.RunPython(add_sp, backwards),

    ]



