# Generated by Django 4.0.1 on 2022-12-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0016_run_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField()),
                ('username', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(max_length=150)),
                ('name_id', models.IntegerField()),
                ('run', models.IntegerField()),
                ('price', models.FloatField()),
                ('qty', models.IntegerField(null=True)),
                ('sold', models.IntegerField(null=True)),
                ('gs', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('completion_time', models.CharField(max_length=50, null=True)),
                ('gem', models.CharField(max_length=250, null=True)),
                ('perk', models.CharField(max_length=250, null=True)),
                ('approved', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sold_items',
                'unique_together': {('server_id', 'name_id', 'price', 'qty', 'sold', 'completion_time', 'status', 'gs', 'gem', 'perk', 'username')},
            },
        ),
    ]
