# Generated by Django 4.0.1 on 2022-12-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0016_run_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='completion_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='gem',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='gs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='perk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='sold',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='avail',
            field=models.IntegerField(null=True),
        ),
    ]
