# Generated by Django 4.0.1 on 2022-12-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0017_solditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
