# Generated by Django 4.0.1 on 2022-12-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0018_servers_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='avail',
            field=models.IntegerField(null=True),
        ),
    ]
