# Generated by Django 4.0.1 on 2022-12-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwmarketapp', '0020_authusertrackeditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='authusertrackeditems',
            name='server_id',
            field=models.IntegerField(null=True),
        ),
    ]
